name: Swift CI (Linux)

on:
  push:
    branches: [root]
  pull_request:
    branches: [root]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: sersoft-gmbh/SwiftyActions@v1
        with:
          release-version: 5.3
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v --configuration release
      - uses: actions/upload-artifact@v2
        with:
          name: termina
          path: ./build/x86_64-unknown-linux-gnu/release/Termina
